#!/usr/bin/env python3
"""Fit three moving-process-zone fracture classes against initiation and R-curves.

The fitted classes are:

* ``ceramic``: toughness decreases with temperature and the response remains
  essentially brittle at every temperature;
* ``weakT``: an intermediate, FCC-like toughness with weak temperature
  dependence and a moderate rising resistance curve;
* ``DBTT``: a brittle low-temperature shelf and a tough high-temperature
  branch whose rising resistance is generated by the evolving process zone.

The objective never fits a scalar backstress, scalar emission saturation,
per-step emission cap, or stored-energy cleavage offset.  It compares robust
R-curve summaries (Theil-Sen-like median slope, median developed resistance,
and a diagnostic robust saturation fit) rather than individual noisy events.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import math
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd
from scipy.optimize import differential_evolution, least_squares, minimize

from arrhenius_fracture import sharp_front as sf
from arrhenius_fracture.config import make_emergent_config


# ---------------------------------------------------------------------------
# Command-line serialization
# ---------------------------------------------------------------------------

def fs(x: Any) -> str:
    return f"{float(x):.16g}"


def parse_float_pair(text: str) -> tuple[float, float]:
    vals = [float(x) for x in str(text).replace(",", " ").split() if x]
    if len(vals) != 2 or vals[1] <= vals[0]:
        raise argparse.ArgumentTypeError("expected two increasing values")
    return vals[0], vals[1]


def parse_float_list(text: str) -> list[float]:
    return [float(x) for x in str(text).replace(",", " ").split() if x]


def row_to_args(row: pd.Series, *, dK: float, Kdot: float, n_advances: int,
                Kmax: float, da_um: float) -> argparse.Namespace:
    cli = [
        "--mode", "1d", "--front-state-model", "moving_pz", "--temperatures", "300",
        "--Kdot", fs(Kdot), "--Kmax", fs(Kmax), "--dt", fs(dK / Kdot),
        "--continue-after-init", "--n-advances", str(n_advances),
        "--sigma-cap-GPa", "0", "--da", fs(da_um * 1.0e-6),
        "--r-pz", fs(row.r_pz_m), "--c-blunt", fs(row.c_blunt),
        "--L-pz", fs(row.mpz_length_m), "--mpz-length-m", fs(row.mpz_length_m),
        "--mpz-n-bins", str(int(row.mpz_n_bins)),
        "--mpz-n-systems", str(int(row.mpz_n_systems)),
        "--mpz-source-sites-per-system", fs(row.mpz_source_sites_per_system),
        "--mpz-source-recovery-rate-s", fs(row.mpz_source_recovery_rate_s),
        "--mpz-source-refresh-length-m", fs(row.mpz_source_refresh_length_m),
        "--mpz-shielding-factors", str(row.mpz_shielding_factors),
        "--mpz-glide-barrier-eV", fs(row.mpz_glide_barrier_eV),
        "--mpz-glide-activation-volume-b3", fs(row.mpz_glide_activation_volume_b3),
        "--mpz-trap-barrier-eV", fs(row.mpz_trap_barrier_eV),
        "--mpz-detrap-barrier-eV", fs(row.mpz_detrap_barrier_eV),
        "--mpz-retained-recovery-barrier-eV", fs(row.mpz_retained_recovery_barrier_eV),
        "--mpz-pair-annihilation-rate-per-count-s",
        fs(row.mpz_pair_annihilation_rate_per_count_s),
        "--bulk-kinetics-model", "emission_derived_peierls_taylor_multihit",
        "--peierls-energy-scale", fs(row.get("pt_peierls_energy_ratio", 0.005)),
        "--peierls-entropy-scale", fs(row.get("pt_peierls_entropy_ratio", 0.005)),
        "--taylor-energy-scale", fs(row.get("pt_taylor_energy_ratio", 0.02)),
        "--taylor-entropy-scale", fs(row.get("pt_taylor_entropy_ratio", 0.02)),
        "--pt-taylor-corr-rho-c", fs(row.get("pt_taylor_corr_rho_c", 1.0e14)),
        "--pt-taylor-renewal-time-s", fs(row.get("pt_taylor_renewal_time_s", 1.0e-9)),
        "--pt-taylor-m-exponent", fs(row.get("pt_taylor_m_exponent", 1.0)),
        "--pt-taylor-m-scale", fs(row.get("pt_taylor_m_scale", 1.0)),
        "--pt-taylor-m-cap", fs(row.get("pt_taylor_m_cap", float("inf"))),
        "--pt-mobile-fraction", fs(row.get("pt_mobile_fraction", 0.01)),
        "--pt-mobile-saturation-density-m2",
        fs(row.get("pt_mobile_saturation_density_m2", 1.0e14)),
        "--cleave-barrier-kind", "exp_floor", "--cleave-exp-T-mode", "linear",
        "--cleave-G00-eV", fs(row.cleave_G00_eV),
        f"--cleave-gT-eV-per-K={fs(row.cleave_gT_eV_per_K)}",
        "--cleave-sigc0-GPa", fs(row.cleave_sigc0_GPa),
        f"--cleave-sT-GPa-per-K={fs(row.cleave_sT_GPa_per_K)}",
        "--cleave-exp-a", fs(row.cleave_exp_a),
        "--cleave-exp-n", fs(row.cleave_exp_n),
        "--cleave-floor-frac", fs(row.cleave_floor_frac),
        f"--cleave-S-hs-kB={fs(row.cleave_S_hs_kB)}",
        "--cleave-sigma-S-GPa", "6", "--cleave-S-hs-power", "2",
        "--emit-barrier-kind", "exp_floor",
        "--emit-G00-eV", fs(row.emit_G00_eV),
        f"--emit-gT-eV-per-K={fs(row.emit_gT_eV_per_K)}",
        "--emit-sigc0-GPa", fs(row.emit_sigc0_GPa),
        f"--emit-sT-GPa-per-K={fs(row.emit_sT_GPa_per_K)}",
        "--emit-exp-a", fs(row.emit_exp_a),
        "--emit-exp-n", fs(row.emit_exp_n),
        "--emit-floor-frac", fs(row.emit_floor_frac),
    ]
    return sf._build_parser().parse_args(cli)


# ---------------------------------------------------------------------------
# Robust R-curve summaries
# ---------------------------------------------------------------------------

def median_pairwise_slope(x: np.ndarray, y: np.ndarray) -> float:
    """Median pairwise slope, robust to event-level R-curve scatter."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    good = np.isfinite(x) & np.isfinite(y)
    x = x[good]
    y = y[good]
    if x.size < 2:
        return float("nan")
    slopes: list[float] = []
    for i in range(x.size - 1):
        dx = x[i + 1 :] - x[i]
        use = np.abs(dx) > 1.0e-12
        if np.any(use):
            slopes.extend(((y[i + 1 :][use] - y[i]) / dx[use]).tolist())
    return float(np.median(slopes)) if slopes else float("nan")


def window_values(x: np.ndarray, y: np.ndarray,
                  window: tuple[float, float]) -> tuple[np.ndarray, np.ndarray]:
    use = (x >= window[0]) & (x <= window[1]) & np.isfinite(x) & np.isfinite(y)
    return x[use], y[use]


def robust_saturation_fit(a_um: np.ndarray, K: np.ndarray) -> dict[str, float]:
    """Fit K=K0+dK*(1-exp(-(a/L)^p)) with a soft-L1 loss.

    The fit is diagnostic.  The optimization objective uses the more robust
    median plateau and median pairwise slopes as its primary R-curve targets.
    """
    a = np.asarray(a_um, dtype=float)
    y = np.asarray(K, dtype=float)
    good = np.isfinite(a) & np.isfinite(y)
    a = a[good]
    y = y[good]
    if a.size < 8:
        return {"sat_K0": float("nan"), "sat_delta_KR": float("nan"),
                "sat_Kss": float("nan"), "sat_length_um": float("nan"),
                "sat_power": float("nan"), "sat_rmse": float("nan")}

    k0 = float(np.median(y[: min(3, y.size)]))
    kss = float(np.median(y[-min(8, y.size) :]))
    d0 = max(kss - k0, 0.05)
    L0 = max(float(np.median(a[a > 0])) if np.any(a > 0) else 200.0, 20.0)
    p0 = 1.0

    def residual(z: np.ndarray) -> np.ndarray:
        K0, dK, logL, logp = z
        L = math.exp(logL)
        p = math.exp(logp)
        pred = K0 + dK * (1.0 - np.exp(-np.power(np.maximum(a, 0.0) / L, p)))
        return pred - y

    lower = np.array([0.0, 0.0, math.log(2.0), math.log(0.15)])
    upper = np.array([100.0, 100.0, math.log(1.0e5), math.log(6.0)])
    try:
        res = least_squares(
            residual, np.array([k0, d0, math.log(L0), math.log(p0)]),
            bounds=(lower, upper), loss="soft_l1", f_scale=0.5, max_nfev=1000,
        )
        K0, dK, logL, logp = res.x
        rmse = float(np.sqrt(np.mean(np.square(residual(res.x)))))
        return {"sat_K0": float(K0), "sat_delta_KR": float(dK),
                "sat_Kss": float(K0 + dK), "sat_length_um": float(math.exp(logL)),
                "sat_power": float(math.exp(logp)), "sat_rmse": rmse}
    except Exception:
        return {"sat_K0": float("nan"), "sat_delta_KR": float("nan"),
                "sat_Kss": float("nan"), "sat_length_um": float("nan"),
                "sat_power": float("nan"), "sat_rmse": float("nan")}


def summarize_rcurve(a_um: Iterable[float], K: Iterable[float],
                     early_window: tuple[float, float],
                     plateau_window: tuple[float, float]) -> dict[str, float]:
    a = np.asarray(list(a_um), dtype=float)
    y = np.asarray(list(K), dtype=float)
    if y.size == 0:
        base = {
            "K_init": float("nan"), "K_plateau": float("nan"),
            "delta_KR": float("nan"), "early_rise_per_100um": float("nan"),
            "plateau_rise_per_100um": float("nan"), "n_early": 0,
            "n_plateau": 0, "roughness_MAD": float("nan"),
        }
        return {**base, **robust_saturation_fit(a, y)}

    xe, ye = window_values(a, y, early_window)
    xp, yp = window_values(a, y, plateau_window)
    early_slope = median_pairwise_slope(xe, ye)
    plateau_slope = median_pairwise_slope(xp, yp)
    Kplateau = float(np.median(yp)) if yp.size else float("nan")
    Kinit = float(y[0])

    # Robust local roughness relative to a 5-event rolling median.
    if y.size >= 5:
        roll = pd.Series(y).rolling(5, center=True, min_periods=1).median().to_numpy()
        roughness = float(np.median(np.abs(y - roll)))
    else:
        roughness = float(np.median(np.abs(y - np.median(y))))

    base = {
        "K_init": Kinit,
        "K_plateau": Kplateau,
        "delta_KR": Kplateau - Kinit if np.isfinite(Kplateau) else float("nan"),
        "early_rise_per_100um": early_slope * 100.0,
        "plateau_rise_per_100um": plateau_slope * 100.0,
        "n_early": int(ye.size), "n_plateau": int(yp.size),
        "roughness_MAD": roughness,
    }
    return {**base, **robust_saturation_fit(a, y)}


# ---------------------------------------------------------------------------
# Reduced moving-PZ simulation
# ---------------------------------------------------------------------------

def simulate(row: pd.Series, T: float, opt: argparse.Namespace) -> dict[str, Any]:
    args = row_to_args(
        row, dK=opt.dK, Kdot=opt.Kdot, n_advances=opt.n_advances,
        Kmax=opt.Kmax, da_um=opt.da_um,
    )
    eng = sf.build_engine(args, make_emergent_config().material)

    # Resolve at most one renewal in each accepted adaptive substep.  This is
    # not a physical event cap: the substep is reduced until the predicted
    # cleavage-clock increment is small, and residual B is retained exactly.
    eng.f.max_advances_per_step = 1

    events: list[dict[str, float]] = []
    max_shield_fraction = 0.0  # evaluated at crack-renewal events
    max_transient_shield_fraction = 0.0
    max_K_shield_MPa_sqrt_m = 0.0
    max_blunt_ratio = 1.0
    min_site_fraction = 1.0
    max_retained = 0.0
    max_active = 0.0
    max_emitted_total = 0.0
    r0 = max(float(eng.f.r0), 1.0e-30)
    current_K = 0.0
    n_substeps = 0
    integration_stalled = False

    def commit_info(Kmpa: float, info: dict[str, Any]) -> None:
        nonlocal max_shield_fraction, max_transient_shield_fraction
        nonlocal max_K_shield_MPa_sqrt_m, max_blunt_ratio, min_site_fraction
        nonlocal max_retained, max_active, max_emitted_total

        Ksh_post = float(info.get("mpz_K_shield_Pa_sqrt_m", 0.0)) / 1.0e6
        max_K_shield_MPa_sqrt_m = max(max_K_shield_MPa_sqrt_m, Ksh_post)
        max_transient_shield_fraction = max(
            max_transient_shield_fraction, Ksh_post / max(Kmpa, 1.0e-12)
        )
        max_blunt_ratio = max(max_blunt_ratio, float(info.get("r_eff", r0)) / r0)
        min_site_fraction = min(
            min_site_fraction, float(info.get("mpz_available_site_fraction", 1.0))
        )
        max_retained = max(
            max_retained, float(info.get("mpz_retained_count", info.get("N_em", 0.0)))
        )
        max_active = max(max_active, float(info.get("mpz_active_count", 0.0)))
        max_emitted_total = max(
            max_emitted_total, float(info.get("mpz_emitted_total", 0.0))
        )

        nfire = int(info.get("n_fire", 0))
        if not nfire:
            return
        Ksh_pre = float(
            info.get("mpz_K_shield_pre_renewal_Pa_sqrt_m",
                     info.get("mpz_K_shield_Pa_sqrt_m", 0.0))
        ) / 1.0e6
        rpre = float(info.get("r_eff_pre_renewal", info.get("r_eff", r0)))
        retained_pre = float(
            info.get("mpz_retained_pre_renewal",
                     info.get("N_em_pre_renewal", info.get("N_em", 0.0)))
        )
        mobile_pre = float(info.get("mpz_mobile_pre_renewal", 0.0))
        site_pre = float(
            info.get("mpz_available_site_fraction_pre_renewal",
                     info.get("mpz_available_site_fraction", 1.0))
        )
        slip_pre = float(info.get("mpz_local_slip_pre_renewal", 0.0))
        emitted_pre = float(
            info.get("mpz_emitted_total_pre_renewal",
                     info.get("mpz_emitted_total", 0.0))
        )
        for _ in range(nfire):
            idx = len(events)
            events.append({
                "event_index": float(idx),
                "a_um": float(idx * opt.da_um),
                "K_MPa_sqrt_m": float(Kmpa),
                "K_shield_MPa_sqrt_m": float(Ksh_pre),
                "shield_fraction": float(Ksh_pre / max(Kmpa, 1.0e-12)),
                "blunt_ratio": float(rpre / r0),
                "retained_count": retained_pre,
                "mobile_count": mobile_pre,
                "available_site_fraction": site_pre,
                "local_slip_count": slip_pre,
                "emitted_total": emitted_pre,
            })
            max_shield_fraction = max(
                max_shield_fraction, Ksh_pre / max(Kmpa, 1.0e-12)
            )
            max_blunt_ratio = max(max_blunt_ratio, rpre / r0)
            min_site_fraction = min(min_site_fraction, site_pre)
            max_retained = max(max_retained, retained_pre)
            max_active = max(max_active, retained_pre + mobile_pre)
            max_emitted_total = max(max_emitted_total, emitted_pre)

    tol_K = max(1.0e-12, 1.0e-12 * opt.Kmax)
    while current_K < opt.Kmax - tol_K and len(events) < opt.n_advances:
        nominal_end = min(current_K + opt.dK, opt.Kmax)
        while current_K < nominal_end - tol_K and len(events) < opt.n_advances:
            if n_substeps >= opt.max_substeps:
                integration_stalled = True
                break

            # Consume any residual completed renewal before adding physical time.
            if float(eng.B) >= 1.0:
                info = eng.step(current_K * 1.0e6, T, 0.0)
                n_substeps += 1
                commit_info(current_K, info)
                if not info.get("fired", False):
                    integration_stalled = True
                    break
                continue

            dK_proposed = nominal_end - current_K
            dt_proposed = dK_proposed / opt.Kdot

            cap = max(float(np.sum(eng.mpz_state.site_capacity)), 1.0e-300)
            avail_fraction = float(np.sum(eng.mpz_state.available_sites)) / cap

            def acceptable(fraction_trial: float) -> bool:
                dK_trial = dK_proposed * fraction_trial
                dt_trial = dt_proposed * fraction_trial
                K_trial = current_K + dK_trial
                if opt.target_dB_substep > 0.0:
                    dB_trial = float(
                        eng.predict_clock_increment(K_trial * 1.0e6, T, dt_trial)
                    )
                    if dB_trial > opt.target_dB_substep:
                        return False
                if (opt.target_emission_hazard_substep > 0.0
                        and avail_fraction > opt.source_active_fraction_min):
                    sig_trial = eng.sigma_tip(K_trial * 1.0e6)
                    H_trial = float(eng.lambda_emit(sig_trial, T)[0] * dt_trial)
                    if H_trial > opt.target_emission_hazard_substep:
                        return False
                return True

            if acceptable(1.0):
                fraction = 1.0
            else:
                lo = 0.0
                hi = 1.0
                for _ in range(36):
                    mid = 0.5 * (lo + hi)
                    if acceptable(mid):
                        lo = mid
                    else:
                        hi = mid
                fraction = max(lo, opt.min_substep_fraction)

            fraction = float(np.clip(fraction, opt.min_substep_fraction, 1.0))
            dK_step = max(dK_proposed * fraction, tol_K)
            dK_step = min(dK_step, dK_proposed)
            dt_step = dK_step / opt.Kdot
            current_K += dK_step
            info = eng.step(current_K * 1.0e6, T, dt_step)
            n_substeps += 1
            commit_info(current_K, info)

        if integration_stalled:
            break

    event_df = pd.DataFrame(events)
    metrics = summarize_rcurve(
        event_df.get("a_um", pd.Series(dtype=float)).to_numpy(),
        event_df.get("K_MPa_sqrt_m", pd.Series(dtype=float)).to_numpy(),
        opt.early_window_um, opt.plateau_window_um,
    )

    def event_median(column: str, window: tuple[float, float]) -> float:
        if event_df.empty or column not in event_df:
            return float("nan")
        use = (event_df.a_um >= window[0]) & (event_df.a_um <= window[1])
        return float(event_df.loc[use, column].median()) if use.any() else float("nan")

    metrics.update({
        "T_K": float(T),
        "n_events": int(len(events)),
        "event_fraction": float(min(len(events) / max(opt.n_advances, 1), 1.0)),
        "completed": bool(len(events) >= opt.n_advances),
        "integration_stalled": bool(integration_stalled),
        "n_substeps": int(n_substeps),
        "max_shield_fraction": float(max_shield_fraction),
        "max_transient_shield_fraction": float(max_transient_shield_fraction),
        "max_K_shield_MPa_sqrt_m": float(max_K_shield_MPa_sqrt_m),
        "max_blunt_ratio": float(max_blunt_ratio),
        "min_site_fraction": float(min_site_fraction),
        "max_retained": float(max_retained),
        "max_active": float(max_active),
        "max_emitted_total": float(max_emitted_total),
        "init_shield_fraction": float(event_df.iloc[0].shield_fraction) if len(event_df) else float("nan"),
        "plateau_shield_fraction": event_median("shield_fraction", opt.plateau_window_um),
        "init_blunt_ratio": float(event_df.iloc[0].blunt_ratio) if len(event_df) else float("nan"),
        "plateau_blunt_ratio": event_median("blunt_ratio", opt.plateau_window_um),
        "init_site_fraction": float(event_df.iloc[0].available_site_fraction) if len(event_df) else float("nan"),
        "plateau_site_fraction": event_median("available_site_fraction", opt.plateau_window_um),
        "plateau_retained_count": event_median("retained_count", opt.plateau_window_um),
        "events": events,
    })
    return metrics


# ---------------------------------------------------------------------------
# Parameter vectors
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ParameterSpec:
    vector_name: str
    row_name: str
    lower: float
    upper: float
    transform: str = "linear"


SPEC_CLEAVE_G = ParameterSpec("cleave_G00_eV", "cleave_G00_eV", 0.6, 4.5)
SPEC_CLEAVE_GT = ParameterSpec("cleave_gT_eV_per_K", "cleave_gT_eV_per_K", -0.0015, 0.0025)
SPEC_CLEAVE_SIG = ParameterSpec("cleave_sigc0_GPa", "cleave_sigc0_GPa", 1.5, 8.0)
SPEC_EMIT_G = ParameterSpec("emit_G00_eV", "emit_G00_eV", 0.6, 3.5)
SPEC_EMIT_GT = ParameterSpec("emit_gT_eV_per_K", "emit_gT_eV_per_K", -0.0015, 0.0030)
SPEC_EMIT_SIG = ParameterSpec("emit_sigc0_GPa", "emit_sigc0_GPa", 0.5, 8.0)
SPEC_SITES = ParameterSpec("log_source_sites", "mpz_source_sites_per_system", math.log(0.5), math.log(300.0), "log")
SPEC_GLIDE = ParameterSpec("mpz_glide_barrier_eV", "mpz_glide_barrier_eV", 0.25, 2.2)
SPEC_TRAP = ParameterSpec("mpz_trap_barrier_eV", "mpz_trap_barrier_eV", 0.25, 2.0)
SPEC_DETRAP = ParameterSpec("mpz_detrap_barrier_eV", "mpz_detrap_barrier_eV", 0.50, 2.8)
SPEC_RETREC = ParameterSpec("mpz_retained_recovery_barrier_eV", "mpz_retained_recovery_barrier_eV", 0.80, 3.2)
SPEC_CBLUNT = ParameterSpec("log_c_blunt", "c_blunt", math.log(0.05), math.log(3.0), "log")
SPEC_SRCREC = ParameterSpec("log_source_recovery_rate", "mpz_source_recovery_rate_s", math.log(1.0e-10), math.log(1.0e-1), "log")
SPEC_REFRESH = ParameterSpec("log_source_refresh_length", "mpz_source_refresh_length_m", math.log(5.0e-7), math.log(2.0e-5), "log")
SPEC_LENGTH = ParameterSpec("log_mpz_length", "mpz_length_m", math.log(1.0e-5), math.log(2.0e-4), "log")

FIRST_SPECS = [SPEC_CLEAVE_G, SPEC_CLEAVE_GT, SPEC_CLEAVE_SIG,
               SPEC_EMIT_G, SPEC_EMIT_GT, SPEC_EMIT_SIG]
RCURVE_SPECS = [SPEC_SITES, SPEC_GLIDE, SPEC_TRAP, SPEC_DETRAP,
                SPEC_RETREC, SPEC_CBLUNT, SPEC_SRCREC, SPEC_REFRESH,
                SPEC_LENGTH]
REDUCED_SPECS = [SPEC_CLEAVE_G, SPEC_CLEAVE_GT, SPEC_EMIT_G, SPEC_EMIT_GT,
                 SPEC_SITES, SPEC_GLIDE, SPEC_TRAP, SPEC_DETRAP,
                 SPEC_RETREC, SPEC_CBLUNT]
FULL_SPECS = FIRST_SPECS + RCURVE_SPECS


def parameter_specs(profile: str) -> list[ParameterSpec]:
    if profile == "first":
        return list(FIRST_SPECS)
    if profile == "rcurve":
        return list(RCURVE_SPECS)
    if profile == "reduced":
        return list(REDUCED_SPECS)
    if profile == "full":
        return list(FULL_SPECS)
    raise ValueError(profile)


def row_to_vector(row: pd.Series, specs: list[ParameterSpec]) -> np.ndarray:
    vals = []
    for spec in specs:
        value = float(row[spec.row_name])
        vals.append(math.log(max(value, 1.0e-300)) if spec.transform == "log" else value)
    return np.asarray(vals, dtype=float)


def vector_to_row(base: pd.Series, x: np.ndarray,
                  specs: list[ParameterSpec]) -> pd.Series:
    row = base.copy()
    for value, spec in zip(np.asarray(x, dtype=float), specs):
        row[spec.row_name] = math.exp(float(value)) if spec.transform == "log" else float(value)
    # High-stress cleavage entropy is deliberately not a class-fit knob in v9.1.
    row["cleave_S_hs_kB"] = 0.0
    return row


# ---------------------------------------------------------------------------
# Objective
# ---------------------------------------------------------------------------

def pseudo_huber(z: float, delta: float = 1.0) -> float:
    if not np.isfinite(z):
        return 25.0
    # Cap a single pathological state from numerically overwhelming every
    # other physical target while preserving a strong rejection penalty.
    z = float(np.clip(z, -100.0 * delta, 100.0 * delta))
    return float(delta * delta * (math.sqrt(1.0 + (z / delta) ** 2) - 1.0))


def interval_loss(value: float, low: float, high: float, scale: float = 1.0) -> float:
    if not np.isfinite(value):
        return 25.0
    if value < low:
        return pseudo_huber((value - low) / max(scale, 1.0e-12))
    if value > high:
        return pseudo_huber((value - high) / max(scale, 1.0e-12))
    return 0.0


def monotonic_violation(values: np.ndarray, *, increasing: bool,
                        tolerance: float = 0.25) -> float:
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v)]
    if v.size < 2:
        return 10.0
    d = np.diff(v)
    bad = np.maximum((-d if increasing else d) - tolerance, 0.0)
    return float(np.sum(np.square(bad / max(tolerance, 0.25))))


def _plastic_indicator(q: dict[str, Any], prefix: str) -> float:
    """Compact finite indicator of shielding/blunting at initiation or plateau."""
    shield = float(q.get(f"{prefix}_shield_fraction", float("nan")))
    blunt = float(q.get(f"{prefix}_blunt_ratio", float("nan")))
    candidates = []
    if np.isfinite(shield):
        candidates.append(max(shield, 0.0))
    if np.isfinite(blunt):
        candidates.append(max(0.15 * (blunt - 1.0), 0.0))
    return max(candidates) if candidates else float("nan")


def class_constraint_loss(klass: str, sims: list[dict[str, Any]], mode: str = "joint") -> tuple[float, dict[str, float]]:
    ordered = sorted(sims, key=lambda q: q["T_K"])
    T = np.asarray([q["T_K"] for q in ordered], dtype=float)
    Ki = np.asarray([q["K_init"] for q in ordered], dtype=float)
    Kp = np.asarray([q["K_plateau"] for q in ordered], dtype=float)
    dR = np.asarray([q["delta_KR"] for q in ordered], dtype=float)

    use_first = mode in ("first", "joint")
    use_rcurve = mode in ("rcurve", "joint")
    parts: dict[str, float] = {}
    if klass == "ceramic":
        if use_first:
            parts["first_temperature_order"] = monotonic_violation(Ki, increasing=False)
        if use_rcurve:
            parts["plateau_temperature_order"] = monotonic_violation(Kp, increasing=False)
            parts["brittle_Rcurve"] = float(np.nansum([
                interval_loss(v, 0.0, 1.5, 0.5) for v in dR
            ]))
    elif klass == "weakT":
        if use_first:
            finite_i = Ki[np.isfinite(Ki)]
            parts["first_passage_flatness"] = interval_loss(
                float(np.ptp(finite_i)) if finite_i.size else float("nan"),
                0.0, 2.5, 0.75,
            )
        if use_rcurve:
            finite_p = Kp[np.isfinite(Kp)]
            parts["plateau_flatness"] = interval_loss(
                float(np.ptp(finite_p)) if finite_p.size else float("nan"),
                0.0, 3.0, 1.0,
            )
            parts["moderate_Rcurve"] = float(np.nansum([
                interval_loss(v, 3.0, 7.0, 1.0) for v in dR
            ]))
    elif klass == "DBTT":
        low = T <= 500.0
        high = T >= 900.0
        low_Ki = float(np.nanmedian(Ki[low])) if np.any(low) else float("nan")
        high_Ki = float(np.nanmedian(Ki[high])) if np.any(high) else float("nan")
        low_Kp = high_Kp = low_dR = high_dR = float("nan")
        if use_rcurve:
            low_Kp = float(np.nanmedian(Kp[low])) if np.any(low) else float("nan")
            high_Kp = float(np.nanmedian(Kp[high])) if np.any(high) else float("nan")
            low_dR = float(np.nanmedian(dR[low])) if np.any(low) else float("nan")
            high_dR = float(np.nanmedian(dR[high])) if np.any(high) else float("nan")
        if use_first:
            parts["first_temperature_order"] = monotonic_violation(
                Ki, increasing=True, tolerance=0.75
            )
            parts["transition_first_passage"] = interval_loss(
                high_Ki - low_Ki, 18.0, 40.0, 4.0
            )
            # A cleavage-only thermal slope is not sufficient for the DBTT
            # class.  Plastic shielding/blunting must be weak on the low-T
            # shelf and measurably developed before the high-T first event.
            low_init_plastic = np.nanmedian([
                _plastic_indicator(q, "init") for q in ordered
                if q["T_K"] <= 500.0
            ])
            high_init_plastic = np.nanmedian([
                _plastic_indicator(q, "init") for q in ordered
                if q["T_K"] >= 900.0
            ])
            parts["first_passage_microstructure_switch"] = (
                interval_loss(float(low_init_plastic), 0.0, 0.12, 0.04)
                + interval_loss(float(high_init_plastic), 0.06, 0.80, 0.05)
            )
        if use_rcurve:
            parts["plateau_temperature_order"] = monotonic_violation(
                Kp, increasing=True, tolerance=1.0
            )
            parts["transition_plateau"] = interval_loss(
                high_Kp - low_Kp, 25.0, 50.0, 5.0
            )
            parts["lowT_brittleness"] = interval_loss(low_dR, 0.0, 1.5, 0.5)
            parts["highT_rising_resistance"] = interval_loss(
                high_dR, 7.0, 14.0, 2.0
            )

            # The DBTT high-temperature branch must be connected to evolved
            # shielding/blunting, not only to a direct cleavage-barrier slope.
            low_sims = [q for q in ordered if q["T_K"] <= 500.0]
            high_sims = [q for q in ordered if q["T_K"] >= 900.0]
            low_plastic = np.nanmedian([
                _plastic_indicator(q, "plateau") for q in low_sims
            ]) if low_sims else float("nan")
            high_plastic = np.nanmedian([
                _plastic_indicator(q, "plateau") for q in high_sims
            ]) if high_sims else float("nan")
            parts["microstructure_switch"] = (
                interval_loss(float(low_plastic), 0.0, 0.15, 0.05)
                + interval_loss(float(high_plastic), 0.12, 0.80, 0.08)
            )
    else:
        raise ValueError(f"unknown class: {klass}")
    return float(sum(parts.values())), parts


def state_regularization_loss(sims: list[dict[str, Any]], row: pd.Series) -> tuple[float, dict[str, float]]:
    shield = 0.0
    sites = 0.0
    geometry = 0.0
    incomplete = 0.0
    for q in sims:
        shield += interval_loss(float(q["max_shield_fraction"]), 0.0, 0.90, 0.05)
        shield += interval_loss(float(q.get("max_K_shield_MPa_sqrt_m", 0.0)),
                                0.0, 100.0, 10.0)
        # Exact source exhaustion at essentially every crack position behaves
        # like a hidden threshold.  Small depletion is allowed and expected.
        sites += interval_loss(float(q["min_site_fraction"]), 0.005, 1.0, 0.01)
        r_ratio_limit = max(float(row.mpz_length_m) / max(float(row.r_pz_m), 1.0e-30), 2.0)
        geometry += interval_loss(float(q["max_blunt_ratio"]), 1.0, r_ratio_limit, 2.0)
        incomplete += 20.0 * (1.0 - float(q["event_fraction"])) ** 2
    parts = {"shielding_bound": shield, "source_inventory": sites,
             "blunting_geometry": geometry, "incomplete_growth": incomplete}
    return float(sum(parts.values())), parts


def point_target_loss(targets: pd.DataFrame,
                      sims: list[dict[str, Any]],
                      mode: str = "joint") -> tuple[float, list[dict[str, Any]]]:
    by_T = {float(q["T_K"]): q for q in sims}
    total = 0.0
    details: list[dict[str, Any]] = []
    use_first = mode in ("first", "joint")
    use_rcurve = mode in ("rcurve", "joint")
    for _, t in targets.iterrows():
        q = by_T.get(float(t.T_K))
        if q is None:
            total += 100.0
            continue
        weight = float(t.get("weight", 1.0))
        components: dict[str, float] = {}
        if use_first:
            components["K_init"] = pseudo_huber(
                (q["K_init"] - t.K_init_target) / t.K_init_scale
            )
        if use_rcurve:
            components.update({
                "K_plateau": pseudo_huber(
                    (q["K_plateau"] - t.K_plateau_target) / t.K_plateau_scale
                ),
                "early_slope": pseudo_huber(
                    (q["early_rise_per_100um"] - t.early_rise_per_100um_target)
                    / t.early_rise_scale
                ),
                "plateau_slope": pseudo_huber(
                    (q["plateau_rise_per_100um"] - t.plateau_rise_per_100um_target)
                    / t.plateau_rise_scale
                ),
                "delta_KR_range": interval_loss(
                    q["delta_KR"], float(t.delta_KR_min),
                    float(t.delta_KR_max), 1.0
                ),
            })
        score = weight * float(sum(components.values()))
        total += score
        details.append({"T_K": float(t.T_K), "score": score, **components})
    return total, details


def objective_for_class(base: pd.Series, targets: pd.DataFrame, klass: str,
                        opt: argparse.Namespace, specs: list[ParameterSpec]):
    Ts = targets.T_K.to_numpy(dtype=float)
    cache: dict[tuple[float, ...], tuple[float, pd.Series, list[dict[str, Any]], dict[str, Any]]] = {}

    def evaluate(x: np.ndarray, details: bool = False):
        key = tuple(np.round(np.asarray(x, dtype=float), 11))
        if key not in cache:
            row = vector_to_row(base, np.asarray(x, dtype=float), specs)
            sims = [simulate(row, T, opt) for T in Ts]
            point, point_rows = point_target_loss(targets, sims, opt.objective_mode)
            class_loss, class_parts = class_constraint_loss(klass, sims, opt.objective_mode)
            state_loss, state_parts = state_regularization_loss(sims, row)
            total = (
                opt.w_points * point + opt.w_class * class_loss
                + opt.w_state * state_loss
            )
            payload = {
                "point": point, "class": class_loss, "state": state_loss,
                "class_parts": class_parts, "state_parts": state_parts,
                "point_rows": point_rows,
            }
            cache[key] = (float(total), row, sims, payload)
        result = cache[key]
        return result if details else result[0]

    return evaluate


# ---------------------------------------------------------------------------
# Outputs and plots
# ---------------------------------------------------------------------------

def flatten_metrics(klass: str, sims: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    metrics: list[dict[str, Any]] = []
    events: list[dict[str, Any]] = []
    for q in sims:
        rec = {k: v for k, v in q.items() if k != "events"}
        metrics.append({"target_class": klass, **rec})
        for ev in q["events"]:
            events.append({"target_class": klass, "T_K": q["T_K"], **ev})
    return metrics, events


def save_summary_plots(out: Path, metrics: pd.DataFrame, events: pd.DataFrame,
                       targets: pd.DataFrame) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return

    classes = [x for x in ("ceramic", "weakT", "DBTT") if x in set(metrics.target_class)]
    fig, axes = plt.subplots(2, 2, figsize=(11.5, 8.5))
    for klass in classes:
        m = metrics[metrics.target_class == klass].sort_values("T_K")
        t = targets[targets.target_class == klass].sort_values("T_K")
        axes[0, 0].plot(m.T_K, m.K_init, "o-", label=f"{klass} fit")
        axes[0, 0].plot(t.T_K, t.K_init_target, "--", label=f"{klass} target")
        axes[0, 1].plot(m.T_K, m.K_plateau, "o-", label=f"{klass} fit")
        axes[0, 1].plot(t.T_K, t.K_plateau_target, "--", label=f"{klass} target")
        axes[1, 0].plot(m.T_K, m.delta_KR, "o-", label=klass)
        axes[1, 1].plot(m.T_K, m.early_rise_per_100um, "o-", label=klass)
    axes[0, 0].set_title("First passage"); axes[0, 0].set_ylabel("K [MPa√m]")
    axes[0, 1].set_title("Median developed resistance"); axes[0, 1].set_ylabel("K [MPa√m]")
    axes[1, 0].set_title("R-curve increment"); axes[1, 0].set_ylabel("ΔK_R [MPa√m]")
    axes[1, 1].set_title("Robust early R-curve slope"); axes[1, 1].set_ylabel("MPa√m per 100 μm")
    for ax in axes.flat:
        ax.set_xlabel("Temperature [K]")
        ax.grid(True, alpha=0.25)
    axes[0, 0].legend(fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(out / "three_class_target_comparison.png", dpi=180)
    plt.close(fig)

    if events.empty:
        return
    available_T = sorted(set(events.T_K.astype(float)))
    requested = [300.0, 700.0, 1100.0]
    selected = [min(available_T, key=lambda x: abs(x - t)) for t in requested]
    selected = list(dict.fromkeys(selected))
    fig, axes = plt.subplots(len(classes), len(selected),
                             figsize=(4.2 * len(selected), 3.2 * len(classes)),
                             squeeze=False)
    for i, klass in enumerate(classes):
        for j, T in enumerate(selected):
            e = events[(events.target_class == klass) & (events.T_K == T)]
            ax = axes[i, j]
            ax.plot(e.a_um, e.K_MPa_sqrt_m, "o-", ms=3)
            ax.set_title(f"{klass}, {T:g} K")
            ax.set_xlabel("Crack extension [μm]")
            ax.set_ylabel("K event [MPa√m]")
            ax.grid(True, alpha=0.25)
    fig.tight_layout()
    fig.savefig(out / "three_class_representative_Rcurves.png", dpi=180)
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main optimization
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--initial", default="mpz_three_class_initial_guesses.csv")
    ap.add_argument("--targets", default="mpz_three_class_design_targets.csv")
    ap.add_argument("--out", default="runs/mpz_v9_1_three_class_fit")
    ap.add_argument("--classes", default="ceramic weakT DBTT")
    ap.add_argument("--temperatures", default="300 500 700 900 1100")
    ap.add_argument("--fit-profile", choices=("first", "rcurve", "reduced", "full"), default="reduced")
    ap.add_argument("--objective-mode", choices=("first", "rcurve", "joint"), default="joint")
    ap.add_argument("--optimizer", choices=("de", "powell"), default="de")
    ap.add_argument("--dK", type=float, default=0.10)
    ap.add_argument("--Kdot", type=float, default=0.005)
    ap.add_argument("--Kmax", type=float, default=65.0)
    ap.add_argument("--da-um", type=float, default=5.0)
    ap.add_argument("--n-advances", type=int, default=201,
                    help="201 events at da=5 um spans 0-1000 um.")
    ap.add_argument("--early-window-um", type=parse_float_pair, default=(20.0, 220.0))
    ap.add_argument("--plateau-window-um", type=parse_float_pair, default=(700.0, 1000.0))
    ap.add_argument("--target-dB-substep", type=float, default=0.20,
                    help="Adaptive 1-D event-resolution target for cleavage-clock increments.")
    ap.add_argument("--target-emission-hazard-substep", type=float, default=1.0,
                    help="Adaptive finite-site depletion target per accepted substep.")
    ap.add_argument("--source-active-fraction-min", type=float, default=1e-4,
                    help="Stop emission-hazard substepping after the finite source inventory is nearly depleted.")
    ap.add_argument("--min-substep-fraction", type=float, default=1e-8)
    ap.add_argument("--max-substeps", type=int, default=2000000)
    ap.add_argument("--w-points", type=float, default=1.0)
    ap.add_argument("--w-class", type=float, default=2.0)
    ap.add_argument("--w-state", type=float, default=1.0)
    ap.add_argument("--popsize", type=int, default=10)
    ap.add_argument("--maxiter", type=int, default=60)
    ap.add_argument("--maxfev", type=int, default=5000)
    ap.add_argument("--tol", type=float, default=0.01)
    ap.add_argument("--seed", type=int, default=91071)
    ap.add_argument("--smoke", action="store_true",
                    help="Evaluate initial rows without optimization.")
    ap.add_argument("--resume", action="store_true",
                    help="Warm-start each class from its saved best checkpoint.")
    ap.add_argument("--skip-completed", action="store_true")
    ap.add_argument("--no-polish", action="store_true")
    a = ap.parse_args()

    if a.dK <= 0 or a.Kdot <= 0 or a.da_um <= 0:
        raise SystemExit("dK, Kdot, and da must be positive")
    if (a.objective_mode != "first" and
            a.plateau_window_um[1] > (a.n_advances - 1) * a.da_um + 1.0e-9):
        raise SystemExit(
            "plateau window extends beyond the requested crack-growth history; "
            "increase --n-advances or reduce --plateau-window-um"
        )

    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "class_results").mkdir(exist_ok=True)
    (out / "checkpoints").mkdir(exist_ok=True)

    init = pd.read_csv(a.initial).set_index("target_class", drop=False)
    targets_all = pd.read_csv(a.targets)
    wanted_T = set(parse_float_list(a.temperatures))
    classes = a.classes.replace(",", " ").split()
    specs = parameter_specs(a.fit_profile)

    final_rows: list[dict[str, Any]] = []
    all_metrics: list[dict[str, Any]] = []
    all_events: list[dict[str, Any]] = []
    all_scores: list[dict[str, Any]] = []

    for iclass, klass in enumerate(classes):
        class_dir = out / "class_results" / klass
        class_dir.mkdir(parents=True, exist_ok=True)
        completed_file = class_dir / "parameters.csv"
        if a.skip_completed and completed_file.exists():
            row_df = pd.read_csv(completed_file)
            metrics_df = pd.read_csv(class_dir / "metrics.csv")
            events_df = pd.read_csv(class_dir / "events.csv")
            final_rows.extend(row_df.to_dict("records"))
            all_metrics.extend(metrics_df.to_dict("records"))
            all_events.extend(events_df.to_dict("records"))
            print(f"SKIP completed {klass}")
            continue

        if klass not in init.index:
            raise SystemExit(f"missing initial row for {klass}")
        base = init.loc[klass].copy()
        targets = targets_all[
            (targets_all.target_class.astype(str) == klass)
            & targets_all.T_K.astype(float).isin(wanted_T)
        ].sort_values("T_K")
        if targets.empty:
            raise SystemExit(f"no selected targets for {klass}")

        fun = objective_for_class(base, targets, klass, a, specs)
        x0 = row_to_vector(base, specs)
        checkpoint = out / "checkpoints" / f"{klass}_best.json"
        if a.resume and checkpoint.exists():
            payload = json.loads(checkpoint.read_text())
            saved = np.asarray(payload.get("x", []), dtype=float)
            if saved.size == x0.size:
                x0 = saved
                print(f"{klass}: warm-starting from {checkpoint}")

        if a.smoke:
            xbest = x0
            optimizer_meta = {"mode": "smoke", "success": True, "message": "initial evaluation"}
        else:
            iteration = {"n": 0}

            def callback(intermediate_result=None, x=None, convergence=None):
                iteration["n"] += 1
                if intermediate_result is not None and hasattr(intermediate_result, "x"):
                    xb = np.asarray(intermediate_result.x, dtype=float)
                    fb = float(intermediate_result.fun)
                elif intermediate_result is not None and np.ndim(intermediate_result) > 0:
                    xb = np.asarray(intermediate_result, dtype=float)
                    fb = float(fun(xb))
                elif x is not None and np.ndim(x) > 0:
                    xb = np.asarray(x, dtype=float)
                    fb = float(fun(xb))
                else:
                    return False
                checkpoint.write_text(json.dumps({
                    "target_class": klass, "fit_profile": a.fit_profile,
                    "iteration": iteration["n"], "score": fb,
                    "x": xb.tolist(), "parameter_names": [s.vector_name for s in specs],
                }, indent=2))
                return False

            bounds = [(s.lower, s.upper) for s in specs]
            if a.optimizer == "de":
                result = differential_evolution(
                    fun, bounds=bounds, seed=a.seed + iclass, popsize=a.popsize,
                    maxiter=a.maxiter, tol=a.tol, polish=not a.no_polish,
                    workers=1, updating="immediate", x0=x0, callback=callback,
                )
                xbest = np.asarray(result.x, dtype=float)
                optimizer_meta = {
                    "mode": "differential_evolution", "success": bool(result.success),
                    "message": str(result.message), "nit": int(result.nit),
                    "nfev": int(result.nfev), "fun": float(result.fun),
                }
            else:
                iteration = {"n": 0}

                def powell_callback(xk):
                    iteration["n"] += 1
                    xb = np.asarray(xk, dtype=float)
                    checkpoint.write_text(json.dumps({
                        "target_class": klass, "fit_profile": a.fit_profile,
                        "iteration": iteration["n"], "score": float(fun(xb)),
                        "x": xb.tolist(),
                        "parameter_names": [s.vector_name for s in specs],
                    }, indent=2))

                result = minimize(
                    fun, x0, method="Powell", bounds=bounds,
                    callback=powell_callback,
                    options={"maxiter": a.maxiter, "maxfev": a.maxfev,
                             "xtol": 1.0e-4, "ftol": a.tol, "disp": True},
                )
                xbest = np.asarray(result.x, dtype=float)
                optimizer_meta = {
                    "mode": "Powell", "success": bool(result.success),
                    "message": str(result.message), "nit": int(getattr(result, "nit", 0)),
                    "nfev": int(getattr(result, "nfev", 0)), "fun": float(result.fun),
                }

        score, row, sims, parts = fun(xbest, details=True)
        row["fit_score"] = score
        row["fit_point_component"] = parts["point"]
        row["fit_class_component"] = parts["class"]
        row["fit_state_component"] = parts["state"]
        row["fit_profile"] = a.fit_profile
        row["status"] = (
            "INITIAL_SMOKE_ONLY" if a.smoke
            else "FITTED_MPZ_V9_1_THREE_CLASS"
        )
        row["design_target_file"] = str(a.targets)

        mrows, erows = flatten_metrics(klass, sims)
        pd.DataFrame([dict(row)]).to_csv(completed_file, index=False)
        pd.DataFrame(mrows).to_csv(class_dir / "metrics.csv", index=False)
        pd.DataFrame(erows).to_csv(class_dir / "events.csv", index=False)
        (class_dir / "score.json").write_text(json.dumps({
            "target_class": klass, "score": score, "components": parts,
            "optimizer": optimizer_meta,
        }, indent=2))

        final_rows.append(dict(row))
        all_metrics.extend(mrows)
        all_events.extend(erows)
        all_scores.append({
            "target_class": klass, "score": score,
            "point_component": parts["point"],
            "class_component": parts["class"],
            "state_component": parts["state"],
            **{f"class_{k}": v for k, v in parts["class_parts"].items()},
            **{f"state_{k}": v for k, v in parts["state_parts"].items()},
        })
        print(klass, "score", score,
              {k: parts[k] for k in ("point", "class", "state")})

    param_df = pd.DataFrame(final_rows)
    metrics_df = pd.DataFrame(all_metrics)
    events_df = pd.DataFrame(all_events)
    scores_df = pd.DataFrame(all_scores)
    param_df.to_csv(out / "mpz_three_class_parameters.csv", index=False)
    metrics_df.to_csv(out / "mpz_three_class_metrics.csv", index=False)
    events_df.to_csv(out / "mpz_three_class_event_Rcurves.csv", index=False)
    scores_df.to_csv(out / "mpz_three_class_score_components.csv", index=False)
    metrics_df.to_json(out / "mpz_three_class_predictions.json", orient="records", indent=2)
    (out / "run_config.json").write_text(json.dumps({
        **vars(a),
        "early_window_um": list(a.early_window_um),
        "plateau_window_um": list(a.plateau_window_um),
        "parameter_names": [s.vector_name for s in specs],
    }, indent=2))

    selected_targets = targets_all[
        targets_all.target_class.astype(str).isin(classes)
        & targets_all.T_K.astype(float).isin(wanted_T)
    ]
    save_summary_plots(out, metrics_df, events_df, selected_targets)


if __name__ == "__main__":
    main()
