#!/usr/bin/env bash
set -euo pipefail

ROOT=${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
CAMPAIGN_ROOT=${CAMPAIGN_ROOT:-$ROOT/runs/v10_0_5_17_v10227_paper4_anisotropic_300_1000K_20um_smoke_v1}

export ROOT CAMPAIGN_ROOT
export TEMPERATURES=${TEMPERATURES:-"300 1000"}
export TARGET_EXT_UM=${TARGET_EXT_UM:-20}
export STEPS=${STEPS:-100000}
export BASE_HAZARD_SEED=${BASE_HAZARD_SEED:-1720}
export CRYSTAL_THETA_DEG=${CRYSTAL_THETA_DEG:-30}
export MIN_GLOBAL_FORWARD=${MIN_GLOBAL_FORWARD:-0.05}
export GENERATE_SOLVER_PLOTS=${GENERATE_SOLVER_PLOTS:-1}
export SNAPSHOT_BY_EXT_UM=${SNAPSHOT_BY_EXT_UM:-5}
export SAVE_SNAPSHOTS=${SAVE_SNAPSHOTS:-5}
export SNAPSHOT_COLS=${SNAPSHOT_COLS:-3}
export MAX_JOBS=${MAX_JOBS:-2}
export RUN_J_SCALE_DIAGNOSTIC=${RUN_J_SCALE_DIAGNOSTIC:-1}
export J_DIAGNOSTIC_STRICT=${J_DIAGNOSTIC_STRICT:-0}

exec bash "$ROOT/run_v10_0_5_17_v10227_four_class_campaign.sh"
