"""v10.0.5 parallel crack-opening and tensor-resolved emission coupling.

This layer keeps the certified v10.0.3 transaction/lifecycle implementation but:
- uses raw, non-normalized per-system FEM drive factors;
- applies each directional factor only inside the system stress entering its hazard;
- uses exact finite-source depletion without multiplying the hazard result again;
- returns the raw signed elastic shielding generated by the evolving MPZ state.
"""
from __future__ import annotations

import copy
import math
from typing import Any

import numpy as np

from . import mixed_mode_first_passage_v9_11 as v911
from .kinetic_campaign_czm import (
    KineticCampaignCZMConfig,
    CampaignKineticMPZState,
    apply_pf_manifest_to_mpz_config,
)
from .kinetic_campaign_czm_v1001 import (
    ResetSafeDevelopedStateDiagnosticCZMFrontEngine,
)
from .kinetic_campaign_czm_v1003 import CampaignAwareV1003TipEngineMixin

STATE_MODEL = "kinetic_campaign_czm"
MODEL_ID = "FEM_CZM_parallel_opening_tensor_emission_v10_0_5"


class TensorResolvedCampaignKineticMPZState(CampaignKineticMPZState):
    """Campaign state with direct per-system drive factors and exact depletion."""

    tensor_resolved_emission_state = True
    directional_multiplier_applied_after_hazard = False

    @staticmethod
    def drive_factors(
        values: np.ndarray | None,
        n_systems: int,
    ) -> np.ndarray:
        if values is None:
            return np.ones(int(n_systems), dtype=float)
        raw = np.asarray(values, dtype=float).reshape(-1)
        if raw.size != int(n_systems):
            raise ValueError(
                f"expected {n_systems} tensor-resolved drive factors; found {raw.size}"
            )
        if not np.all(np.isfinite(raw)):
            raise ValueError("tensor-resolved drive factors must be finite")
        if np.any(raw < 0.0):
            raise ValueError("tensor-resolved drive factors must be nonnegative")
        return raw.copy()

    def emit_exact(
        self,
        dt_s: float,
        sigma_opening_Pa: float,
        T_K: float,
        system_weights: np.ndarray | None = None,
    ) -> dict[str, Any]:
        dt = max(float(dt_s), 0.0)
        factors = self.drive_factors(system_weights, self.n_systems)
        sigma_back = self.taylor_backstress_Pa()
        sigma_emit = np.maximum(
            factors * max(float(sigma_opening_Pa), 0.0) - sigma_back,
            0.0,
        )
        rates = np.maximum(self.manifest.emission.rate(sigma_emit, T_K), 0.0)
        available0 = np.maximum(self.available_sites.copy(), 0.0)
        probability = 1.0 - np.exp(-np.minimum(rates * dt, 700.0))

        # Exact finite-source depletion. The tensor factor already entered the
        # barrier through sigma_emit; it is intentionally not applied again.
        emitted_system = np.minimum(available0 * probability, available0)
        self.available_sites = np.clip(
            available0 - emitted_system,
            0.0,
            self.site_capacity,
        )
        nsrc = max(min(int(self.cfg.source_bin_count), self.n_bins), 1)
        self.mobile[:, :nsrc] += emitted_system[:, None] / nsrc
        self.accumulated_slip[:, :nsrc] += emitted_system[:, None] / nsrc
        emitted = float(np.sum(emitted_system))
        self.emitted_total += emitted
        self.cumulative_emitted += emitted
        self.last_emitted_per_system = emitted_system.copy()
        self.last_emission_rate_per_system_s = rates.copy()
        self.last_sigma_emit_per_system_Pa = sigma_emit.copy()
        return {
            "dN_emit": emitted,
            "dN_emit_per_system": emitted_system.tolist(),
            "lambda_emit_per_system_s-1": rates.tolist(),
            "emission_probability_per_system": probability.tolist(),
            "slip_system_drive_factors": factors.tolist(),
            "sigma_emission_backstress_per_system_Pa": sigma_back.tolist(),
            "sigma_emission_effective_per_system_Pa": sigma_emit.tolist(),
            "emission_backstress_density_per_system_m2": (
                self.last_local_density_per_system_m2.tolist()
            ),
            "directional_multiplier_applied_after_hazard": False,
        }


class ParallelOpeningEmissionCZMFrontEngine(
    ResetSafeDevelopedStateDiagnosticCZMFrontEngine
):
    """Campaign engine with tensor-resolved emission and uncapped shielding."""

    state_model_detail = (
        "pf_v10_1_7_1_parallel_opening_tensor_emission_reset_safe_v1005"
    )
    tensor_resolved_parallel_coupling = True
    fit_derived_shielding_cap_active = False

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._install_tensor_state()

    def _install_tensor_state(self) -> None:
        self.mpz_state = TensorResolvedCampaignKineticMPZState(
            self.mpz_config,
            self.manifest,
            b=self.b,
            G_Pa=self.G,
            kinetic_cfg=self.kinetic_config,
        )
        self._sync_compat()

    def reset(self) -> None:
        super().reset()
        self._install_tensor_state()

    def active_K_shielding(self) -> float:
        if not self.kinetic_config.active_shielding:
            return 0.0
        raw = float(self._active_shielding_raw())
        if not self.kinetic_config.signed_active_shielding:
            raw = max(raw, 0.0)
        return raw

    def stress_channels(
        self,
        K_open: float,
        K_cleave: float,
        system_weights: np.ndarray | None = None,
    ) -> dict[str, Any]:
        opening = self.sigma_opening_tip(K_open)
        cleavage = self.sigma_cleavage_tip(K_cleave)
        factors = TensorResolvedCampaignKineticMPZState.drive_factors(
            system_weights,
            self.mpz_state.n_systems,
        )
        back = self.mpz_state.taylor_backstress_Pa()
        emission = np.maximum(factors * opening - back, 0.0)
        raw_shield = float(self._active_shielding_raw())
        effective_shield = float(self.active_K_shielding())
        out = {
            "K_open_Pa_sqrt_m": float(K_open),
            "K_cleave_input_Pa_sqrt_m": float(K_cleave),
            "K_shield_raw_Pa_sqrt_m": raw_shield,
            "K_shield_effective_Pa_sqrt_m": effective_shield,
            "sigma_opening_tip_Pa": opening,
            "sigma_cleave_eff_Pa": cleavage,
            "sigma_emission_backstress_Pa": float(np.mean(back)),
            "sigma_emission_effective_Pa": float(np.mean(emission)),
            "sigma_emission_backstress_per_system_Pa": back.tolist(),
            "sigma_emission_effective_per_system_Pa": emission.tolist(),
            "slip_system_directional_weights": factors.tolist(),
            "slip_system_drive_factors": factors.tolist(),
            "fit_derived_shielding_cap_active": False,
            "manifest_max_K_shield_ignored": True,
        }
        self._last_channels = copy.deepcopy(out)
        return out

    def audit_payload(self) -> dict[str, Any]:
        payload = super().audit_payload()
        payload.update({
            "model": MODEL_ID,
            "front_state_model": STATE_MODEL,
            "state_model_detail": self.state_model_detail,
            "tensor_resolved_parallel_coupling": True,
            "emission_drive_applied_once_inside_hazard": True,
            "directional_multiplier_applied_after_hazard": False,
            "active_shielding_is_raw_signed_elastic_state": True,
            "fit_derived_shielding_cap_active": False,
            "manifest_max_K_shield_ignored": True,
            "response_classification_gate_active": False,
            "material_reparameterization_performed": False,
        })
        return payload


def engine_factory_v1005(
    original_build,
    context,
    mm,
    row,
    manifest,
    kinetic_cfg: KineticCampaignCZMConfig,
    registry,
):
    """Build the live v10.0.5 engine without changing material manifests."""

    def build(parsed_args, material):
        base = original_build(parsed_args, material)
        cfg = v911.build_mpz_config(mm, row)
        apply_pf_manifest_to_mpz_config(cfg, manifest, kinetic_cfg)
        base.f.r0 = 1.0e-6
        base.f.L_pz = cfg.length_m
        base.f.c_blunt = float(manifest.c_blunt)
        base.f.nu0_c = float(manifest.cleavage.attempt_frequency_s)
        base.f.nu0_e = float(manifest.emission.attempt_frequency_s)
        base.f.m_hits = 3.0
        base.f.tau_c = 1.0e-6
        base.f.sigma_cap = 0.0
        base.f.dN_cap = math.inf
        base.f.N_sat = math.inf
        base.f.recover_k = 0.0
        base.f.k_shield = 0.0
        base.f.chi_shield = 0.0
        base.f.v_emb_b3 = 0.0

        Engine = type(
            "ParallelOpeningEmissionKineticCZMEngineV1005",
            (
                CampaignAwareV1003TipEngineMixin,
                ParallelOpeningEmissionCZMFrontEngine,
            ),
            {
                "supports_progressive_kinetic_czm": True,
                "supports_tensor_resolved_parallel_coupling": True,
                "integration_point_release": "10.0.5",
            },
        )
        eng = Engine(
            base.f,
            base.cb,
            base.eb,
            base.G,
            base.nu,
            base.b,
            cfg,
            manifest,
            kinetic_cfg,
        )
        eng._mm_init(context)
        if getattr(eng, "state_model", None) != STATE_MODEL:
            raise RuntimeError(
                "v10.0.5 factory constructed the wrong state model: "
                f"{getattr(eng, 'state_model', None)!r}"
            )
        if not bool(getattr(eng, "tensor_resolved_parallel_coupling", False)):
            raise RuntimeError(
                "v10.0.5 factory constructed an engine without parallel coupling"
            )
        registry.append(eng)
        return eng

    return build


__all__ = [
    "STATE_MODEL",
    "MODEL_ID",
    "TensorResolvedCampaignKineticMPZState",
    "ParallelOpeningEmissionCZMFrontEngine",
    "engine_factory_v1005",
]
