"""Aligned stateful-voiding reduction for the one-dimensional V3 model."""

from .mechanics import (
    AlignedVoidMechanicsBackend,
    MechanicsMapDomainError,
    MechanicsResponse,
    ResponseMapNode,
    TensorProductResponseMap,
    TopologyRegime,
    held_out_geometry_family,
)
from .materials import (
    COMMON_ELASTIC_ROW_ID,
    COMMON_SITE_POPULATION_ROW_ID,
    COMMON_SPECIMEN_LOADING_ROW_ID,
    COMMON_VOID_KINETICS_ROW_ID,
    FRACTURE_ROWS,
    MaterialBundle,
    load_exact_fracture_rows,
    material_field_mapping_audit,
    paired_case_ledger,
    pilot_material_bundles,
    require_complete_material_mapping,
)
from .oracle import export_v5_oracle, readiness
from .state import (
    HazardClock,
    LengthLedgers,
    MechanicsRepresentation,
    OneDStateV3,
    OneDVoidState,
    VoidPhase,
    deserialize,
    fingerprint,
    no_void_downgrade,
    no_void_upgrade,
    serialize,
)
from .trajectory import MonotonicPrototypePlan, run_monotonic_prototype
from .transitions import (
    advance_birth,
    advance_embryo,
    connect_ligament,
    continue_downstream_child,
    grow_cavity,
    nucleate_downstream_child,
    promote_cavity,
    seed_cavity,
)

__all__ = [
    "AlignedVoidMechanicsBackend",
    "COMMON_ELASTIC_ROW_ID",
    "COMMON_SITE_POPULATION_ROW_ID",
    "COMMON_SPECIMEN_LOADING_ROW_ID",
    "COMMON_VOID_KINETICS_ROW_ID",
    "FRACTURE_ROWS",
    "HazardClock",
    "LengthLedgers",
    "MechanicsMapDomainError",
    "MechanicsRepresentation",
    "MechanicsResponse",
    "MaterialBundle",
    "MonotonicPrototypePlan",
    "OneDStateV3",
    "OneDVoidState",
    "ResponseMapNode",
    "TensorProductResponseMap",
    "TopologyRegime",
    "VoidPhase",
    "advance_birth",
    "advance_embryo",
    "connect_ligament",
    "continue_downstream_child",
    "deserialize",
    "export_v5_oracle",
    "fingerprint",
    "grow_cavity",
    "held_out_geometry_family",
    "load_exact_fracture_rows",
    "material_field_mapping_audit",
    "no_void_downgrade",
    "no_void_upgrade",
    "nucleate_downstream_child",
    "paired_case_ledger",
    "pilot_material_bundles",
    "promote_cavity",
    "readiness",
    "run_monotonic_prototype",
    "require_complete_material_mapping",
    "seed_cavity",
    "serialize",
]
