#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import pandas as pd

def main():
 p=argparse.ArgumentParser();p.add_argument("--pf",type=Path,required=True);p.add_argument("--fem",type=Path,required=True);p.add_argument("--out",type=Path,required=True);a=p.parse_args();o=a.out;o.mkdir(parents=True,exist_ok=True);pf=json.loads(a.pf.read_text());fem=json.loads(a.fem.read_text())
 (o/"oneD_v2_pf_source_fixture.json").write_text(json.dumps(pf,indent=2)+"\n");(o/"oneD_v2_femczm_source_fixture.json").write_text(json.dumps(fem,indent=2)+"\n")
 rows=[]
 specs={"PF":[("mobile","count/bin","mobile",True),("retained","count/bin","retained",True),("accumulated_slip","count/bin","local_slip",True),("wake_mobile","count/bin","wake_mobile",True),("wake_retained","count/bin","wake_retained",True),("available_sites","count/system","available_sites",True),("B","action","cleavage_action",True),("K_prev","Pa sqrt(m)","previous_native_drive",True),("threshold stream/RNG","state","threshold_rng_snapshot",False)],"FEMCZM":[("mobile","count/bin","mobile",True),("retained","count/bin","retained",True),("accumulated_slip","count/bin","local_slip",True),("time_s","s","time_s",True),("emitted_total","count","emitted_total",True),("advance_total_m","m","crack_advance",True),("cleavage action/threshold","action","cleavage_action_threshold",False),("threshold stream/RNG","state","threshold_rng_snapshot",False),("geometry transaction","mesh/path","geometry_snapshot",False)]}
 for owner,items in specs.items():
  for source,units,field,serial in items:rows.append({"source_owner":owner,"production_state_field":source,"units":units,"v2_adapter_field":field,"serialization_status":"EXACT" if serial else "DRIVER_OWNED_NOT_IN_STATE_FIXTURE","exact_comparison_status":"PASS_SNAPSHOT_RESTORE" if serial else "REQUIRES_INSTRUMENTED_DRIVER_DIAGNOSTIC"})
 pd.DataFrame(rows).to_csv(o/"oneD_v2_source_state_sufficiency_matrix.csv",index=False)
 pd.DataFrame([pf,fem]).to_csv(o/"oneD_v2_backend_lifecycle_fixture_results.csv",index=False)
 cols=["availability_status","extension_um","reaction_coefficient","compliance","native_J_per_U2","native_KJ_per_U","qualified_G_per_U2","qualified_KG_per_U"]
 pd.DataFrame([{"availability_status":"BLOCKED_ACTUAL_PRODUCTION_OPERATOR_MAP_NOT_GENERATED"}],columns=cols).to_csv(o/"oneD_v2_pf_mechanics_map.csv",index=False)
 pd.DataFrame([{"availability_status":"BLOCKED_ACTUAL_ZERO_THICKNESS_MAP_NOT_GENERATED"}],columns=cols).to_csv(o/"oneD_v2_femczm_mechanics_map.csv",index=False)
 reports={
 "ONE_D_V2_SOURCE_STATE_ADAPTER_AUDIT.md":"The actual PF `UnifiedMPZFrontEngine/UnifiedMPZState` and FEM/CZM `MovingProcessZoneState` v9.11 were instantiated in their owning repositories. Array/scalar process-zone snapshots restore bitwise fingerprints. The sufficiency matrix identifies driver-owned cleavage thresholds, RNG, and geometry transactions that are not present in the MPZ state objects.",
 "ONE_D_V2_BACKEND_LIFECYCLE_AUDIT.md":"`CommonEventLifecyclePolicy` was removed. PF and FEM/CZM now have separate lifecycle policies. PF source fixtures exercise no-event, emission-only, cleavage crossing, one-renewal, and rollback. FEM/CZM fixtures exercise no-event, emission-only, MPZ translation/renewal, and rollback; cleavage crossing, threshold renewal, RNG restore, rejected subdivision, and atomic geometry rollback remain driver-owned. Request exactly four bounded 3–5-event instrumented diagnostics: PF Peak 1000 K, PF DBTT 1000 K, FEM/CZM Peak 1000 K, and FEM/CZM DBTT 1000 K. These diagnostics must serialize complete pre/trial/post state and RNG snapshots; no long 2-D run is requested.",
 "ONE_D_V2_PF_MECHANICS_MAP_QUALIFICATION.md":"BLOCKED. No candidate-independent 0–1000 µm map generated by the exact production sharp-wake operator is committed. Existing stochastic trajectories and mesh-width diagnostics cannot be repurposed as a standardized forward map. PF quantities must remain model-native/discrete and must not be labelled continuum G.",
 "ONE_D_V2_FEMCZM_MECHANICS_MAP_QUALIFICATION.md":"BLOCKED. Existing strict-cut checkpoints qualify selected physical paths only through roughly 100 µm; they are not a standardized straight-path 0–1000 µm map. A new deterministic zero-thickness plane-strain map must record reaction, compliance, native J/KJ, energy/compliance/VCCT G/KG, scaling residuals, interpolation error, bounds, uncertainty, and mesh fingerprints.",
 "ONE_D_V2_1000K_FORWARD_BASELINE_GATE.md":"NOT RUN — GATE BLOCKED. Neither qualified mechanics map exists and full backend transactional lifecycle parity has not passed. Peak/DBTT reduced baselines and both four-class campaigns remain unlaunched; canonical output tables remain empty and no campaign result is claimed."}
 for n,t in reports.items():(o/n).write_text("# "+n[:-3].replace("_"," ").title()+"\n\n"+t+"\n")
 decision={"source_fixture_gate":"PARTIAL_PASS","full_transaction_gate":"REQUIRES_FOUR_BOUNDED_INSTRUMENTED_DIAGNOSTICS","pf_map_gate":"BLOCKED","femczm_map_gate":"BLOCKED","1000K_baseline_gate":"NOT_RUN","campaigns_launched":False,"canonical_parameters_changed":False}
 (o/"oneD_v2_backend_gate_decision.json").write_text(json.dumps(decision,indent=2)+"\n")
if __name__=="__main__":main()
