from pathlib import Path
p=Path('/mnt/data/patch_cleave/run_v8_compare_1d_2d_K_sweep.py')
s=p.read_text()
# Add parser args before keep-existing
old='''    ap.add_argument("--stop-after-first-2d-fire", action=argparse.BooleanOptionalAction, default=True,\n                    help="Stop each v8 2-D comparison run after the first accepted crack advance. This makes the comparison match V1, which normally stops after its first advance. Use --no-stop-after-first-2d-fire for propagation-after-init diagnostics.")\n    ap.add_argument("--keep-existing", action="store_true")\n'''
new='''    ap.add_argument("--stop-after-first-2d-fire", action=argparse.BooleanOptionalAction, default=True,\n                    help="Stop each v8 2-D comparison run after the first accepted crack advance. This makes the comparison match V1, which normally stops after its first advance. Use --no-stop-after-first-2d-fire for propagation-after-init diagnostics.")\n    # Cleavage free-energy surface controls, passed through to both V1 and v8.\n    ap.add_argument("--cleave-barrier-kind", choices=["classic", "exp_floor"], default=None)\n    ap.add_argument("--cleave-G00-eV", type=float, default=None)\n    ap.add_argument("--cleave-gT-eV-per-K", type=float, default=None)\n    ap.add_argument("--cleave-sigc0-GPa", type=float, default=None)\n    ap.add_argument("--cleave-sT-GPa-per-K", type=float, default=None)\n    ap.add_argument("--cleave-exp-a", type=float, default=None)\n    ap.add_argument("--cleave-exp-n", type=float, default=None)\n    ap.add_argument("--cleave-floor-frac", type=float, default=None)\n    ap.add_argument("--cleave-floor-min-eV", type=float, default=None)\n    ap.add_argument("--cleave-floor-max-frac", type=float, default=None)\n    ap.add_argument("--cleave-Tref-K", type=float, default=None)\n    ap.add_argument("--cleave-exp-T-mode", choices=["linear", "mu_scale"], default=None)\n    ap.add_argument("--cleave-mu-dlnmu-dT-per-K", type=float, default=None)\n    ap.add_argument("--cleave-G0-mu-power", type=float, default=None)\n    ap.add_argument("--cleave-sigc-mu-power", type=float, default=None)\n    ap.add_argument("--cleave-S-hs-kB", type=float, default=None)\n    ap.add_argument("--cleave-sigma-S-GPa", type=float, default=None)\n    ap.add_argument("--cleave-S-hs-power", type=float, default=None)\n    ap.add_argument("--cleave-S-hs-dT-per-K", type=float, default=None)\n    ap.add_argument("--cleave-S-hs-Tref-K", type=float, default=None)\n    ap.add_argument("--keep-existing", action="store_true")\n'''
if old not in s: raise SystemExit('parser add marker not found')
s=s.replace(old,new)
# Add pass-through to common after storage common
old='''    if args.storage_model == "fixed_fraction":\n        common += ["--fixed-retained-fraction", str(args.fixed_retained_fraction)]\n\n    rows: List[Dict[str, object]] = []\n'''
new='''    if args.storage_model == "fixed_fraction":\n        common += ["--fixed-retained-fraction", str(args.fixed_retained_fraction)]\n    cleave_passthrough = [\n        ("--cleave-barrier-kind", args.cleave_barrier_kind),\n        ("--cleave-G00-eV", args.cleave_G00_eV),\n        ("--cleave-gT-eV-per-K", args.cleave_gT_eV_per_K),\n        ("--cleave-sigc0-GPa", args.cleave_sigc0_GPa),\n        ("--cleave-sT-GPa-per-K", args.cleave_sT_GPa_per_K),\n        ("--cleave-exp-a", args.cleave_exp_a),\n        ("--cleave-exp-n", args.cleave_exp_n),\n        ("--cleave-floor-frac", args.cleave_floor_frac),\n        ("--cleave-floor-min-eV", args.cleave_floor_min_eV),\n        ("--cleave-floor-max-frac", args.cleave_floor_max_frac),\n        ("--cleave-Tref-K", args.cleave_Tref_K),\n        ("--cleave-exp-T-mode", args.cleave_exp_T_mode),\n        ("--cleave-mu-dlnmu-dT-per-K", args.cleave_mu_dlnmu_dT_per_K),\n        ("--cleave-G0-mu-power", args.cleave_G0_mu_power),\n        ("--cleave-sigc-mu-power", args.cleave_sigc_mu_power),\n        ("--cleave-S-hs-kB", args.cleave_S_hs_kB),\n        ("--cleave-sigma-S-GPa", args.cleave_sigma_S_GPa),\n        ("--cleave-S-hs-power", args.cleave_S_hs_power),\n        ("--cleave-S-hs-dT-per-K", args.cleave_S_hs_dT_per_K),\n        ("--cleave-S-hs-Tref-K", args.cleave_S_hs_Tref_K),\n    ]\n    for flag, val in cleave_passthrough:\n        if val is not None:\n            common += [flag, str(val)]\n\n    rows: List[Dict[str, object]] = []\n'''
if old not in s: raise SystemExit('common marker not found')
s=s.replace(old,new)
# Add v1 summary diagnostics after sigma_tip_GPa maybe
old='''            "sigma_tip_GPa": float(r.sigma_tip) / 1e9,\n            "cyclic_plastic_work_J": "",\n'''
new='''            "sigma_tip_GPa": float(r.sigma_tip) / 1e9,\n            "G_cleave_raw_eV": _as_float(getattr(r, "G_cleave_raw_eV", float("nan"))),\n            "G_cleave_eff_eV": _as_float(getattr(r, "G_cleave_eff_eV", float("nan"))),\n            "S_cleave_kB": _as_float(getattr(r, "S_cleave_kB", float("nan"))),\n            "dGcleave_dsigma_eV_per_GPa": _as_float(getattr(r, "dGcleave_dsigma_eV_per_GPa", float("nan"))),\n            "vstar_cleave_b3": _as_float(getattr(r, "vstar_cleave_b3", float("nan"))),\n            "G_emit_eV": _as_float(getattr(r, "G_emit_eV", float("nan"))),\n            "S_emit_kB": _as_float(getattr(r, "S_emit_kB", float("nan"))),\n            "cyclic_plastic_work_J": "",\n'''
if old not in s: raise SystemExit('v1 row diag marker not found')
s=s.replace(old,new,1)
# Add v8 summary diagnostics after sigma_tip_GPa second occurrence
old='''            "sigma_tip_GPa": float(s.sigma_tip_Pa) / 1e9,\n            "cyclic_plastic_work_J": float(s.cyclic_plastic_work_J),\n'''
new='''            "sigma_tip_GPa": float(s.sigma_tip_Pa) / 1e9,\n            "G_cleave_raw_eV": _as_float(getattr(s, "G_cleave_raw_eV", float("nan"))),\n            "G_cleave_eff_eV": _as_float(getattr(s, "G_cleave_eff_eV", float("nan"))),\n            "S_cleave_kB": _as_float(getattr(s, "S_cleave_kB", float("nan"))),\n            "dGcleave_dsigma_eV_per_GPa": _as_float(getattr(s, "dGcleave_dsigma_eV_per_GPa", float("nan"))),\n            "vstar_cleave_b3": _as_float(getattr(s, "vstar_cleave_b3", float("nan"))),\n            "cyclic_plastic_work_J": float(s.cyclic_plastic_work_J),\n'''
if old not in s: raise SystemExit('v8 row diag marker not found')
s=s.replace(old,new)
# Add paired cleave columns after mu_emit_ratio
old='''            "mu_emit_ratio_v8_over_v1": v8["mu_emit_per_cycle"] / max(v1["mu_emit_per_cycle"], 1e-300),\n            "sigma_tip_ratio_v8_over_v1": v8["sigma_tip_GPa"] / max(v1["sigma_tip_GPa"], 1e-300),\n'''
new='''            "mu_emit_ratio_v8_over_v1": v8["mu_emit_per_cycle"] / max(v1["mu_emit_per_cycle"], 1e-300),\n            "G_cleave_eff_v8_minus_v1_eV": v8.get("G_cleave_eff_eV", float("nan")) - v1.get("G_cleave_eff_eV", float("nan")),\n            "S_cleave_v8_minus_v1_kB": v8.get("S_cleave_kB", float("nan")) - v1.get("S_cleave_kB", float("nan")),\n            "sigma_tip_ratio_v8_over_v1": v8["sigma_tip_GPa"] / max(v1["sigma_tip_GPa"], 1e-300),\n'''
if old not in s: raise SystemExit('paired diag marker not found')
s=s.replace(old,new)
p.write_text(s)
