#!/usr/bin/env bash
set -euo pipefail

# Run one crystal orientation across the four canonical temperature-response regimes.
# Usage:
#   THETA=30 STEPS=4500 bash run_regime_sweep_v8_single_orientation.sh regime_sweep_theta30
#   THETA=45 STEPS=4500 bash run_regime_sweep_v8_single_orientation.sh regime_sweep_theta45
# Optional environment variables:
#   TEMPS="300 400 500 600 700 800 900 1000"
#   REGIMES="ceramic peak weakT DBTT"
#   FORCE=1   # rerun completed cases

OUT=${1:-regime_sweep_v8_theta${THETA:-30}}
THETA=${THETA:-30}
STEPS=${STEPS:-4500}
TEMPS=${TEMPS:-"300 400 500 600 700 800 900 1000"}
REGIMES=${REGIMES:-"ceramic peak weakT DBTT"}
mkdir -p "$OUT"

# Shared 2-D multifront / cluster-J / restrictive branch-clock settings from v8.
COMMON="--mode 2d --nx 50 --ny 100 \
  --tip-h-fine 0.35e-6 --tip-ratio 1.25 \
  --dU 2e-7 --dt 8.4 --steps ${STEPS} --n-stagger 2 \
  --save-snapshots 8 --snapshot-cols 4 --print-every 250 \
  --crystal-aniso --crystal-compete --crystal-branch --crystal-material branchy \
  --cleave-gamma-aniso 2.0 --branch-overdrive-ratio 0.95 \
  --branch-fp-min-ratio 0.98 --branch-clock-target 1.0 \
  --branch-clock-angle-tol-deg 10 \
  --branch-secondary-min-K-ratio 0.90 --branch-secondary-min-K-MPa 10.0 \
  --branch-secondary-min-lambda 0.0 \
  --branch-starved-suppression-radius 120e-6 \
  --branch-starved-K-ratio 0.40 --branch-starved-lambda 1e-20 \
  --branch-starved-max-length-factor 4.0 \
  --retire-stagnant-branches --branch-stagnant-lag 120e-6 \
  --branch-stagnant-K-ratio 0.25 --branch-stagnant-lambda 1e-25 \
  --branch-stagnant-steps 25 --branch-stagnant-no-fire-steps 80 \
  --branch-share-mode hazard --branch-hazard-sharpness 2.0 \
  --branch-energy-share hazard-budget \
  --emit-S-T-c0-kB=-20 --emit-S-T-c1=0.02 --emit-S-sigma-max-kB=8 \
  --multihit-m 3 --multihit-tau 1e-6 \
  --emb-sat-frac 1 \
  --adaptive-events --adaptive-event-target 0.35 --adaptive-min-frac 1e-8 \
  --adaptive-grow 4.0 --max-fronts 32 --branch-spacing 50 \
  --da-phys 2e-6 --j-decomposition cluster \
  --rJ-cluster 10e-6 --rJ-outer 12e-6 --branch-resolve-length 20e-6 \
  --local-J-clearance-factor 1.0 --min-J-active-elems 12 \
  --local-J-handoff-min-K-ratio 0.60"

regime_flags() {
  case "$1" in
    ceramic)
      # Canonical ceramic-like: no shielding, unbounded emission ledger, lower H0.
      echo "--cleave-H0-eV 2.6 --cleave-shield-chi 0.00 --n-sat inf"
      ;;
    peak)
      # Canonical peak: mild shielding, unbounded emission ledger, larger H0.
      echo "--cleave-H0-eV 3.6 --cleave-shield-chi 0.10 --n-sat inf"
      ;;
    weakT)
      # Canonical weakly T-dependent: light shielding plus finite saturation.
      echo "--cleave-H0-eV 4.0 --cleave-shield-chi 0.20 --n-sat 1500"
      ;;
    DBTT)
      # Canonical DBTT-like: strong shielding plus finite saturation.
      echo "--cleave-H0-eV 6.0 --cleave-shield-chi 0.60 --n-sat 2000"
      ;;
    *)
      echo "Unknown regime: $1" >&2
      return 2
      ;;
  esac
}

cat > "$OUT/README_regime_sweep.txt" <<EOF2
Regime sweep generated by run_regime_sweep_v8_single_orientation.sh
THETA=${THETA}
STEPS=${STEPS}
TEMPS=${TEMPS}
REGIMES=${REGIMES}

Canonical conditions from arrhenius_fracture.regime_map:
  ceramic : chi=0.00, n_sat=inf,  H0=2.6 eV
  peak    : chi=0.10, n_sat=inf,  H0=3.6 eV
  weakT   : chi=0.20, n_sat=1500, H0=4.0 eV
  DBTT    : chi=0.60, n_sat=2000, H0=6.0 eV

All cases use emb_sat_frac=1 and the v8 restrictive branch-clock + stagnant-retirement settings.
EOF2

for REG in $REGIMES; do
  FLAGS=$(regime_flags "$REG")
  for T in $TEMPS; do
    CASE="$OUT/${REG}/T${T}_th${THETA}"
    if [[ -f "$CASE/summary.json" && "${FORCE:-0}" != "1" ]]; then
      echo "=== SKIP existing $CASE ==="
      continue
    fi
    mkdir -p "$CASE"
    echo "=== $CASE ==="
    python3 -m arrhenius_fracture.sharp_front $COMMON $FLAGS \
      --temperatures "$T" --crystal-theta-deg "$THETA" --out "$CASE"
  done
  # Per-regime summary as soon as each regime finishes.
  python3 analyze_clusterJ_growth.py "$OUT/${REG}" > "$OUT/${REG}/clusterJ_summary.csv" || true
done

# Global summary across all regimes.
python3 analyze_clusterJ_growth.py "$OUT" > "$OUT/clusterJ_summary_all.csv" || true
